services:
  backend:
    build: ./backend
    ports:
      - "19091:8000"
    volumes:
      - ./backend/goldkeep.db:/app/data/goldkeep.db
      - ./backend/uploads:/app/uploads
    environment:
      - DATABASE_URL=sqlite:////app/data/goldkeep.db
      - UPLOAD_DIR=/app/uploads
      - INITIAL_PASSWORD=f452cbe6326b14f5
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "19090:80"
    depends_on:
      - backend
    restart: unless-stopped


